[package]
name = "shaddup"
version = "0.1.0"
edition = "2024"

[dependencies]
cfg-if = "1.0.0"
nix = { version = "0.29.0", features = ["fs"] }

[target.'cfg(unix)'.dependencies]
nix = "0.29.0"

[features]
allow_unsupported = []
no_op = []
